version: '3.3'

services:
  pulsar-app:
    build: .
    container_name: pulsar-app-dev
    volumes:
      - ./:/app/
    user: '1000:1000'
    network_mode: "host"
    # UID = echo $UID
    # GID = echo $(id -g)

volumes:
  mongo-data:
    driver: local
