command:
  sync:
    source:
      uri: "mongodb+srv://odontofarialima:REDACTED@olivaras.npjhxdt.mongodb.net/?retryWrites=true&w=majority&appName=Olivaras"
      db: "consultorio"
    destination:
      uri: "mongodb+srv://odontofarialima:REDACTED@olivaras.npjhxdt.mongodb.net/?retryWrites=true&w=majority&appName=Olivaras"
      db: "consultorio-dev"
    collections: []
